export enum ROUTES {
  HOME = '/',
  ABOUT = '/about',
  NOT_FOUND = '/not-found',
  ESTATES = '/estates',
  CONTACTS = '/contacts',
  FAQ = '/faq',
  CONTACT_US = '/contact-us',
  TERMS_OF_USE = '/terms-of-use',
  SERVICE_AROUND = '/service-around',
  RENT = '/rent',
  BUY = '/buy',
  RENT_DETAILS = '/rent/details',
  BUY_DETAILS = '/buy/details',
  KNOWLEDGE_REAL_ESTATE = '/knowledge-real-estate',
  MY_ACCOUNT = '/my-account',
  PROFILE = '/my-account/profile',
  MESSAGES = '/my-account/messages',
  LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  FORGOT_PASSWORD = '/auth/forgot-password',
  CONFIRM_REGISTER = '/auth/confirm-register',
  FAVORITES = '/my-account/favorites',
  ORDER = '/my-account/order',
  PAYMENTS = '/my-account/payments',
  INBOXES = '/inboxes',
}
export enum ADS_ROUTES {
  ADS = '/my-account/ads',
  RENT_ADS = '/my-account/ads/rent-ads',
  SELL_ADS = '/my-account/ads/sell-ads',
  SELL_DETAILS = '/my-account/ads/sell-ads/details',
  RENT_DETAILS = '/my-account/ads/rent-ads/details',
}
