export const ROUTES = {
  home: '/',
  about: '/about',
  notFound: '/not-found',
  estates: '/estates',
  contacts: '/contacts',
  faq: '/faq',
  contactUs: '/contact-us',
  termsOfUse: '/terms-of-use',
  serviceAround: '/service-around',
  rent: '/rent',
  buy: '/buy',
  rentDetails: '/rent/details',
  buyDetails: '/buy/details',
} as const;