export const ROUTES = {
  home: '/',
  about: '/about',
  notFound: '/not-found',
  estates: '/estates',
  contacts: '/contacts',
  faq: '/faq',
  contactUs: '/contact-us',
  termsOfUse: '/terms-of-use',
  serviceAround: '/service-around',
  rent: '/rent',
  buy: '/buy',
  rentDetails: '/rent/details',
  buyDetails: '/buy/details',
  knowledgeRealEstate: '/knowledge-real-estate',
  myAccount: '/my-account',
  profile: '/my-account/profile',
  messages: '/my-account/messages',
  login: '/login',
  register: '/register',
  favorites: '/my-account/favorites',
  order: '/my-account/order',
  payments: '/my-account/payments',
} as const

export const ADS_ROUTES = {
  ads: '/my-account/ads',
  rentAds: '/my-account/ads/rent-ads',
  sellAds: '/my-account/ads/sell-ads',
  sellDetails: '/my-account/ads/sell-ads/details',
  rentDetails: '/my-account/ads/rent-ads/details',
} as const
